name: leofortune4
description: A new Flutter project.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=2.19.6 <3.0.0'

dependencies:

  cupertino_icons: ^1.0.2

  flutter:
    sdk: flutter

  flutter_launcher_icons: ^0.11.0
  flutter_native_splash: ^2.2.16
  freezed_annotation: ^2.2.0
  hooks_riverpod: ^2.1.1
  http: ^0.13.5
  intl: ^0.17.0
  json_annotation: ^4.7.0

dev_dependencies:

  build_runner: ^2.3.2

  flutter_lints: ^2.0.0

  flutter_test:
    sdk: flutter

  freezed: ^2.2.1
  json_serializable: ^6.5.4

flutter:

  uses-material-design: true

  assets:
    - assets/images/

flutter_native_splash:
  image: "assets/images/ic_launcher.png"
  color: "212121"

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/images/ic_launcher.png"

  adaptive_icon_background: "#212121"
  adaptive_icon_foreground: "assets/images/ic_launcher.png"
